dbsql
hosoya-yuji/DBSQL pull request #1
Opened 2024-06-19 14:18 UTC by hosoya-yuji

# やったこと
SQL基礎問題を行い基本的なDBの情報を確認、抽出する方法を学びました

# つまづいた点
有名人の第一言語を出す際に第一言語が複数ある国があるので一つに絞るのに悩みました。

2024-06-20 02:27 UTC, cin-sakino requested changes
全体的にインデントが揃っていないので、揃えるようにしましょう！

2024-06-20 02:27 UTC, cin-sakino commented on practice.sql
> +    indep_year ASC
独立記念日が新しい順なので降順を指定しましょう！

2024-06-20 02:27 UTC, cin-sakino commented on practice.sql
> +        MAX(language) AS language
この`MAX(language)`は必要でしょうか？
文字列に対してMAXを使った場合は、辞書のようにa->zで並べたときに最後の方に来るものが返されます。
なので、この取得はあまり意味がないかもれしません。
シンプルに`offical=t`の`language`を取得するだけで良いですよ！

2024-06-22 16:35 UTC, hosoya-yuji commented on practice.sql
> +        MAX(language) AS language
percentageを見落としていました。
percentageを利用して抽出しました。

2024-06-24 01:51 UTC, cin-sakino approved these changes
💯

2024-06-24 12:51 UTC, merged